spring.application.name=QualityReportportal
# enabling https in Spring Security 
# server.port=8080

server.ssl.enabled=false
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=QualityReportPortal
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=qualityreportportal
